# Install the packages required for our desired libvirt environment.
# We store the list of packages in `libvirt_packages` so that in
# theory we can support multiple distributions simply by passing in a
# different list of packages.
- name: Install packages for libvirt
  package:
    name: "{{ libvirt_packages }}"
    state: present
  become: true

- name: Start libvirtd
  service:
    name: "{{ libvirtd_service }}"
    state: started
    enabled: true
  become: true
