---

- name: Remove virtualbmc directories
  file:
    path: "{{ item }}"
    state: absent
  with_items:
    - "/etc/virtualbmc"
    - "/var/log/virtualbmc"
    - "/root/.vbmc/"
  become: true

- name: Stop/disable the Virtual BMCs (virtualbmc >= 1.4.0+)
  service:
    name: "virtualbmc"
    state: "stopped" 
    enabled: false
  become: true
